const Tests = [
	{
		name: 'TWBCs',
		type: 'input',
		value: null,
		extra: null,
	},
	{
		name: 'BFFM',
		type: 'select',
		value: [
			'Malaria parasites have been seen (+ve)',
			'Malaria parasites have not been seen (-ve)',
		],
		extra: 'This test is used to detect the presence of malaria parasites in the blood.',
	},
	{
		name: 'UG',
		type: 'table',
		value: [
			'Color',
			'Reaction',
			'Sugar',
			'Acetone',
			'Albumin',
			'Bile Pigment',
			'Pus Cells',
			'RBCs',
			'Epith Cells',
			'Cast',
			'Crystals',
			'Ova Of',
			'Cysts',
			'Others',
		],
		extra: null,
	},
	{
		name: 'SG',
		type: 'table',
		value: [
			'Appearance',
			'Reaction (PH)',
			'Consistency',

			'ODER',
			'Blood Occult',
			'Mucous',
			'Others',
			'Pus',
			'Flagellstes',
			'E.histolytic',
			'G.lamblia',
			'Worms',
			'RBCs',
			'Others',
		],
		extra: 'This test examines the physical properties of stool, including appearance, consistency, and the presence of occult blood.',
	},
	{
		name: 'CBC',
		type: 'table',
		value: [
			'WBC Count',
			'RBC Count',
			'Hemoglobin',
			'Hematocrit',
			'Platelet Count',
		],
		extra: 'This test measures the different components of the blood including red and white blood cells, hemoglobin, and platelets.',
	},
	{
		name: 'TFT',
		type: 'table',
		value: ['T3', 'T4', 'TSH'],
		extra: 'Thyroid function tests measure the levels of thyroid hormones (T3, T4) and thyroid-stimulating hormone (TSH) in the blood.',
	},
	{
		name: 'LipidProfile',
		type: 'table',
		value: [
			'Total Cholesterol',
			'HDL Cholesterol',
			'LDL Cholesterol',
			'Triglycerides',
		],
		extra: 'A lipid profile measures cholesterol levels in the blood and helps assess the risk of heart disease and stroke.',
	},
	{
		name: 'LiverFunction',
		type: 'table',
		value: ['ALT', 'AST', 'ALP', 'Bilirubin', 'Albumin', 'Total Protein'],
		extra: 'Liver function tests assess the function of the liver and help detect liver diseases.',
	},
	{
		name: 'Urinalysis',
		type: 'table',
		value: [
			'Color',
			'Clarity',
			'pH',
			'Glucose',
			'Protein',
			'Ketones',
			'Blood Cells',
			'Bacteria',
		],
		extra: 'Urinalysis examines the physical and chemical properties of urine and helps diagnose various conditions.',
	},
	{
		name: 'Electrocardiogram',
		type: 'input',
		value: null,
		extra: 'An ECG records the electrical activity of the heart and is used to detect heart rhythm abnormalities and other cardiac conditions.',
	},
	{
		name: 'StoolCulture',
		type: 'input',
		value: null,
		extra: 'This test is used to identify the presence of infectious bacteria, parasites, or other pathogens in stool samples.',
	},
	{
		name: 'ThroatSwab',
		type: 'select',
		value: [
			'Positive for Streptococcus (+ve)',
			'Negative for Streptococcus (-ve)',
		],
		extra: 'A throat swab is used to test for Streptococcus bacteria, which causes strep throat.',
	},
	{
		name: 'CoagulationProfile',
		type: 'table',
		value: ['PT/INR', 'APTT', 'Fibrinogen'],
		extra: "Coagulation tests assess the blood's ability to clot and are used to monitor anticoagulant therapy or diagnose clotting disorders.",
	},
	{
		name: 'BloodGlucose',
		type: 'input',
		value: null,
		extra: 'This test measures the concentration of glucose in the blood and is used to diagnose diabetes or monitor blood sugar levels.',
	},
];

export default Tests;
